bible_verses = [
    "Philippians 4:13 — I can do all things through Christ who strengthens me.",
    "Joshua 1:9 — Be strong and courageous. Do not be afraid; do not be discouraged, for the Lord your God will be with you wherever you go.",
    "Isaiah 40:31 — Those who hope in the Lord will renew their strength. They will soar on wings like eagles.",
    "Proverbs 3:5-6 — Trust in the Lord with all your heart and lean not on your own understanding.",
    "Jeremiah 29:11 — For I know the plans I have for you, declares the Lord, plans to prosper you and not to harm you.",
    "Romans 8:28 — And we know that in all things God works for the good of those who love him.",
    "Galatians 6:9 — Let us not become weary in doing good, for at the proper time we will reap a harvest if we do not give up.",
    "James 1:2-4 — Consider it pure joy whenever you face trials, because the testing of your faith produces perseverance.",
    "Romans 5:3-4 — We also glory in our sufferings, because suffering produces perseverance, perseverance character, and character hope.",
    "Philippians 4:6-7 — Do not be anxious about anything, but in every situation, by prayer and petition, present your requests to God.",
    "Matthew 11:28 — Come to me, all you who are weary and burdened, and I will give you rest.",
    "John 14:27 — Peace I leave with you; my peace I give you. Do not let your hearts be troubled.",
    "Psalm 139:14 — I praise you because I am fearfully and wonderfully made.",
    "Ephesians 2:10 — For we are God's handiwork, created in Christ Jesus to do good works.",
    "2 Timothy 1:7 — For God has not given us a spirit of fear, but of power, love and a sound mind.",
    "Psalm 23:1 — The Lord is my shepherd, I lack nothing.",
    "Isaiah 41:10 — Do not fear, for I am with you; do not be dismayed, for I am your God.",
    "Romans 8:38-39 — Neither death nor life, neither angels nor demons, neither the present nor the future can separate us from the love of God.",
    "Proverbs 31:25 — She is clothed with strength and dignity; she can laugh at the days to come.",
    "Matthew 6:33 — But seek first his kingdom and his righteousness, and all these things will be given to you as well.",
    "John 3:16 — For God so loved the world that he gave his one and only Son, that whoever believes in him shall not perish but have eternal life.",
    "Psalm 46:1 — God is our refuge and strength, an ever-present help in trouble.",
    "Isaiah 26:3 — You will keep in perfect peace those whose minds are steadfast, because they trust in you.",
    "Proverbs 16:3 — Commit to the Lord whatever you do, and he will establish your plans.",
    "Matthew 5:14 — You are the light of the world. A town built on a hill cannot be hidden.",
    "1 Corinthians 13:4-5 — Love is patient, love is kind. It does not envy, it does not boast, it is not proud.",
    "Psalm 37:4 — Take delight in the Lord, and he will give you the desires of your heart.",
    "Hebrews 11:1 — Now faith is confidence in what we hope for and assurance about what we do not see.",
    "1 Peter 5:7 — Cast all your anxiety on him because he cares for you.",
    "Romans 12:2 — Do not conform to the pattern of this world, but be transformed by the renewing of your mind.",
    "Psalm 119:105 — Your word is a lamp for my feet, a light on my path.",
    "Isaiah 43:2 — When you pass through the waters, I will be with you; and when you pass through the rivers, they will not sweep over you.",
    "John 16:33 — In this world you will have trouble. But take heart! I have overcome the world.",
    "Ephesians 6:10 — Finally, be strong in the Lord and in his mighty power.",
    "Proverbs 18:10 — The name of the Lord is a fortified tower; the righteous run to it and are safe.",
    "Lamentations 3:22-23 — Because of the Lord's great love we are not consumed, for his compassions never fail. They are new every morning.",
    "Matthew 19:26 — With man this is impossible, but with God all things are possible.",
    "Psalm 34:18 — The Lord is close to the brokenhearted and saves those who are crushed in spirit.",
    "2 Corinthians 5:7 — For we live by faith, not by sight.",
    "Deuteronomy 31:6 — Be strong and courageous. Do not be afraid or terrified, for the Lord your God goes with you.",
    "Psalm 28:7 — The Lord is my strength and my shield; my heart trusts in him, and he helps me.",
    "Romans 15:13 — May the God of hope fill you with all joy and peace as you trust in him.",
    "Colossians 3:23 — Whatever you do, work at it with all your heart, as working for the Lord.",
    "Proverbs 4:23 — Above all else, guard your heart, for everything you do flows from it.",
    "Isaiah 55:8-9 — For my thoughts are not your thoughts, neither are your ways my ways, declares the Lord.",
    "John 15:5 — I am the vine; you are the branches. If you remain in me and I in you, you will bear much fruit.",
    "Psalm 27:1 — The Lord is my light and my salvation — whom shall I fear?",
    "Habakkuk 3:19 — The Sovereign Lord is my strength; he makes my feet like the feet of a deer.",
    "2 Chronicles 7:14 — If my people, who are called by my name, will humble themselves and pray, I will forgive their sin and will heal their land.",
    "Micah 6:8 — He has shown you what is good. And what does the Lord require of you? To act justly and to love mercy and to walk humbly with your God.",
]